# Create special workspaces
workspace = name:settings,on-created-empty:true
workspace = name:battle.net,on-created-empty:true
workspace = name:steam,on-created-empty:true
workspace = name:screenrecording,on-created-empty:true
workspace = name:bottles,on-created-empty:true
workspace = name:lutris,on-created-empty:true
workspace = name:gameone,on-created-empty:true
workspace = name:gametwo,on-created-empty:true
workspace = name:gamethree,on-created-empty:true
workspace = name:gamefour,on-created-empty:true
workspace = name:gamefive,on-created-empty:true

# Open settings apps in settings workspace
windowrule {
  name = windowrule-1
  workspace = name:settings silent
  match:class = ^(.*)blueman-manager(.*)$
}

windowrule {
  name = windowrule-2
  workspace = name:settings silent
  match:class = ^(.*)pavucontrol(.*)$
}

windowrule {
  name = windowrule-3
  workspace = name:settings silent
  match:class = ^(.*)solaar(.*)$
}

windowrule {
  name = windowrule-4
  workspace = name:settings silent
  match:class = ^(.*)org.rncbc.qjackctl(.*)$
}


# Battle.net
# windowrulev2 = workspace name:battle.net silent,title:^(.*)$BATTLENET(.*)$
# windowrulev2 = tile,title:^(.*)Battle.net(.*)$
# windowrulev2 = fullscreen,title:^(.*)Diablo IV(.*)$
# windowrulev2 = fullscreen,title:^(.*)Starcraft 2(.*)$

# Steam
windowrule {
  name = windowrule-5
  workspace = name:steam silent
  match:class = ^steam$
}

# Lutris
windowrule {
  name = windowrule-6
  workspace = name:lutris silent
  match:class = ^net.lutris.Lutris$
}

# Bottles
windowrule {
    name = wr-bottles-1
    workspace = name:bottles
    fullscreen = on
    match:title = ^(.*)Bottles(.*)$
}

# File dialogs
windowrule {
  name = windowrule-7
  move = ((monitor_w*0.2)) ((monitor_h*0.2))
  size = (monitor_w*0.4) (monitor_h*0.6)
  float = on
  keep_aspect_ratio = on
  border_size = 3
  tag = file_dialog
  opacity = 1.0 0.9
  match:class = xdg-desktop-portal-gtk
}

windowrule {
  name = windowrule-8
  move = ((monitor_w*0.2)) ((monitor_h*0.2))
  size = (monitor_w*0.4) (monitor_h*0.6)
  float = on
  keep_aspect_ratio = on
  border_size = 3
  tag = file_dialog
  opacity = 1.0 0.9
  match:title = ^(.*)(((A|a)ll (F|f)ile)|((O|o)pen (F|f)ile)|((S|s)elect) (F|f)ile|((A|a)ll) (F|f)iles)(.*)$
}

windowrule {
  name = windowrule-09
  move = ((monitor_w*0.2)) ((monitor_h*0.2))
  size = (monitor_w*0.4) (monitor_h*0.6)
  float = on
  keep_aspect_ratio = on
  border_size = 3
  tag = file_dialog
  opacity = 1.0 0.9
  match:title = "All Files"
}


# Ubisoft / Trackmania
# windowrulev2 = workspace name:gameone silent,title:^(.*)Trackmania(.*)$|^(.*)Ubisoft Connect(.*)$
# windowrulev2 = tile,title:^(.*)Trackmania(.*)$|^(.*)Ubisoft Connect(.*)$

# Minecraft
# windowrulev2 = workspace name:gametwo silent,title:^(.*)Minecraft(.*)$|^(.*)PrismLauncher(.*)$
# windowrulev2 = workspace name:gametwo silent,class:^(.*)PrismLauncher(.*)$
# windowrulev2 = tile,class:^(.*)PrismLauncher(.*)$

# Trackmania Nations Forever
# windowrulev2 = workspace name:gamethree silent,class:steam_app_11020
# windowrulev2 = nofocus,class:steam_app_11020,fullscreen:1

# Screen recording
windowrule {
  name = windowrule-9
  workspace = name:screenrecording silent
  match:class = $SCREENRECORDING
}


